package com.notesbanao.portal.transcript;

import java.util.List;

import org.springframework.stereotype.Service;

import com.notesbanao.portal.common.ApiException;
import com.notesbanao.portal.common.PageMeta;
import com.notesbanao.portal.common.Paging;
import com.notesbanao.portal.notes.dto.NoteDto;
import com.notesbanao.portal.store.DemoDataStore;
import com.notesbanao.portal.transcript.dto.GenerateResponse;
import com.notesbanao.portal.transcript.dto.RecoverableResponse;
import com.notesbanao.portal.transcript.dto.TranscriptSessionDto;
import com.notesbanao.portal.wallet.dto.ActivityDto;

/**
 * Turning a recovered transcript into notes.
 *
 * There is no language model here, so the note body is written from a template.
 * The NB Points charge is real work though: it uses the same duration rules the
 * Billing screen displays, and it refuses the same way when the balance is short.
 */
@Service
public class TranscriptService {

    private static final int MAX_PAGE_SIZE = 50;

    private final DemoDataStore store;

    public TranscriptService(DemoDataStore store) {
        this.store = store;
    }

    public RecoverableResponse recoverable(int page, int limit) {
        List<TranscriptSessionDto> all = store.transcripts();
        PageMeta meta = PageMeta.of(page, Paging.limit(limit, 10, MAX_PAGE_SIZE), all.size());
        return new RecoverableResponse(true, Paging.slice(all, meta), meta);
    }

    public GenerateResponse generate(String sessionId) {
        TranscriptSessionDto session = store.transcript(sessionId);
        if (session == null) {
            throw ApiException.notFound("That transcript is no longer available.");
        }

        int durationSeconds = Math.round(session.totalDurationMs() / 1000f);
        int charge = chargeFor(durationSeconds);
        int balance = store.balancePoints();
        if (balance < charge) {
            // Thrown before anything is spent, so a refused generation costs nothing.
            throw ApiException.insufficientPoints(charge, balance);
        }

        store.debitPoints(charge);
        NoteDto note = store.addNote(session.title(), durationSeconds, template(session.title(), durationSeconds));
        store.addActivity(new ActivityDto(null, "point", "capture", "usage", 0, null, null, null,
                -charge, null, null, "INR", "completed", null, null, note.id(), note.id(),
                session.title(), durationSeconds, null));
        store.discardTranscript(sessionId);

        return new GenerateResponse(true, note.id(), charge);
    }

    public void discard(String sessionId) {
        if (!store.discardTranscript(sessionId)) {
            throw ApiException.notFound("That recovery item is already gone.");
        }
    }

    /** The first active duration rule that covers this length. */
    private int chargeFor(int durationSeconds) {
        return store.durationRules().stream()
                .filter(rule -> rule.active() == 1)
                .filter(rule -> rule.min_duration_seconds() <= durationSeconds)
                .filter(rule -> rule.max_duration_seconds() == null
                        || rule.max_duration_seconds() >= durationSeconds)
                .sorted((a, b) -> Integer.compare(a.sort_order(), b.sort_order()))
                .findFirst()
                .map(rule -> rule.charge_points())
                .orElse(1);
    }

    private String template(String title, int durationSeconds) {
        int minutes = Math.round(durationSeconds / 60f);
        return """
                # %s

                > Generated by the Java backend from a recovered transcript (%d minutes).
                > There is no language model in this build, so this body is a template
                > rather than real notes. See TranscriptService in the java_backend project.

                ## Summary

                The recovered transcript for **%s** was converted into a note and charged
                against your NB Points balance using the duration rules on the Billing screen.

                ## What a real note contains

                1. A short summary of the lecture.
                2. Section headings that follow the order the material was taught in.
                3. Definitions, worked examples, and tables where they help.
                4. A closing list of the points worth revising.
                """.formatted(title, minutes, title);
    }
}
