import { NextResponse } from "next/server";
import { getCurrentUser } from "@/demo-backend/session";
import {
  addActivity,
  chargeForDuration,
  createNote,
  debitPoints,
  discardTranscript,
  transcriptSession,
  userRow
} from "@/demo-backend/queries";

type RouteContext = {
  params: Promise<{ sessionId: string }>;
};

/**
 * Turn a recovered transcript into notes.
 *
 * The real backend queues a job, calls an LLM, and finishes minutes later. This
 * build has no LLM, so the note is written immediately from a template — but
 * the NB Points charge is real: it uses the same duration rules the Billing
 * screen displays, and fails the same way when the balance is short.
 */
export async function POST(_request: Request, context: RouteContext) {
  const user = await getCurrentUser();
  if (!user) {
    return NextResponse.json({ ok: false, message: "Not logged in." }, { status: 401 });
  }

  const { sessionId } = await context.params;
  const session = transcriptSession(sessionId);
  if (!session) {
    return NextResponse.json({ ok: false, message: "That transcript is no longer available." }, { status: 404 });
  }

  const durationSeconds = Math.round(session.total_duration_ms / 1000);
  const charge = chargeForDuration(durationSeconds);
  const balance = userRow().balance_points;
  if (balance < charge) {
    return NextResponse.json(
      {
        ok: false,
        message: `This recording costs ${charge} NB Points and you have ${balance}.`,
        userMessage: {
          title: "Not enough NB Points",
          message: `This recording costs ${charge} NB Points and you have ${balance}. Add points to generate these notes.`,
          severity: "attention",
          action: "recharge"
        }
      },
      { status: 402 }
    );
  }

  debitPoints(charge);
  const noteId = createNote({
    title: session.title,
    durationSeconds,
    markdown: demoNotes(session.title, durationSeconds)
  });
  addActivity({
    type: "point",
    kind: "capture",
    point_type: "usage",
    points_delta: -charge,
    status: "completed",
    source_id: noteId,
    reference_id: noteId,
    note_title: session.title,
    duration_seconds: durationSeconds
  });
  discardTranscript(sessionId);

  return NextResponse.json({ ok: true, notes_id: noteId, points_charged: charge });
}

function demoNotes(title: string, durationSeconds: number) {
  const minutes = Math.round(durationSeconds / 60);
  return `# ${title}

> Generated by the demo portal from a recovered transcript (${minutes} minutes).
> There is no LLM in this build, so this body is a template rather than real
> notes — see \`app/api/transcripts/[sessionId]/generate/route.ts\`.

## Summary

The recovered transcript for **${title}** was converted into a note and charged
against your NB Points balance using the duration rules on the Billing screen.

## What a real note contains

1. A short summary of the lecture.
2. Section headings that follow the order the material was taught in.
3. Definitions, worked examples, and tables where they help.
4. A closing list of the points worth revising.

## Try this

- Delete this note from the Notes screen and watch the list update.
- Download it — the PDF is rendered in your browser, not on a server.
- Change the template in the route handler and generate another one.
`;
}
